config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get :favs
      get :testimony
      get :login
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :groupies, :services, :albums, :notes, :verses
    resource :privacy, :blog, :calendar
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    member do
      put :reorder
    end
    resource :photo
    resources :relationships
    resources :people
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resource :stream
    resource :photo
    resources :notes, :prayer_requests, :albums, :attachments
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resources :emails

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :verses, :shares,
            :comments, :prayer_requests, :generated_files

  resources :notes, except: :index

  resource  :setup, :session, :search, :printable_directory, :privacy

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths
    end
  end

  namespace :checkin do
    root to: 'interfaces#show'
    resource :interface
    resources :families, :people, :groups
  end
end

app/models/document.rb
class Document < ActiveRecord::Base

  belongs_to :folder, class_name: 'DocumentFolder', foreign_key: :folder_id, touch: true

  scope :top, -> { where(folder_id: nil) }

  scope_by_site_id

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }
  validates :file, presence: true

  has_attached_file :file, PAPERCLIP_FILE_OPTIONS
  do_not_validate_attachment_file_type :file

  validates_attachment_size :file, less_than: PAPERCLIP_FILE_MAX_SIZE

  include FileImageConcern
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :get_parent_folder, only: %w(index show new)
  before_action :ensure_admin, except: %w(index show download)

  def index
    @folders = (@parent_folder.try(:folders) || DocumentFolder.active.top).order(:name)
    @documents = (@parent_folder.try(:documents) || Document.top).order(:name)
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    if params[:folder]
      @folder = (@parent_folder.try(:folders) || DocumentFolder).new
      render action: 'new_folder'
    else
      @document = (@parent_folder.try(:documents) || Document).new
    end
  end

  def create
    if params[:folder]
      @folder = DocumentFolder.new(folder_params)
      if @folder.save
        redirect_to documents_path(folder_id: @folder), notice: t('documents.create_folder.notice')
      else
        render action: 'new_folder'
      end
    else
      @document = Document.new(document_params)
      if @document.save
        redirect_to document_path(@document), notice: t('documents.create.notice')
      else
        render action: 'new'
      end
    end
  end

  def edit
    if params[:folder]
      @folder = DocumentFolder.find(params[:id])
      render action: 'edit_folder'
    else
      @document = Document.find(params[:id])
    end
  end

  def update
    if params[:folder]
      @folder = DocumentFolder.find(params[:id])
      if @folder.update_attributes(folder_params)
        redirect_to documents_path(folder_id: @folder.folder_id), notice: t('documents.update_folder.notice')
      else
        render action: 'edit_folder'
      end
    else
      @document = Document.find(params[:id])
      if @document.update_attributes(document_params)
        redirect_to documents_path(folder_id: @document.folder_id), notice: t('documents.update.notice')
      else
        render action: 'edit'
      end
    end
  end

  def destroy
    if params[:folder]
      @folder = DocumentFolder.find(params[:id])
      @folder.destroy
      redirect_to documents_path(folder_id: @folder.folder_id), notice: t('documents.delete_folder.notice')
    else
      @document = Document.find(params[:id])
      @document.destroy
      redirect_to documents_path(folder_id: @document.folder_id), notice: t('documents.delete.notice')
    end
  end

  def download
    @document = Document.find(params[:id])
    send_file @document.file.path,
      disposition: params[:inline] ? 'inline' : 'attachment',
      filename: @document.file_file_name,
      type: @document.file.content_type
  end

  private

  def get_parent_folder
    @parent_folder = params[:folder_id] && DocumentFolder.find(params[:folder_id])
  end

  def folder_params
    params.require(:folder).permit(:name, :description, :hidden, :folder_id)
  end

  def document_params
    params.require(:document).permit(:name, :description, :folder_id, :file)
  end

  def feature_enabled?
    unless Setting.get(:features, :documents)
      redirect_to people_path
      false
    end
  end

  def ensure_admin
    unless @logged_in.admin?(:manage_documents)
      render text: t('not_authorized'), layout: true
      false
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper

  def document_icon_class(document)
    case document.try(:file).try(:content_type)
    when /^image/
      'fa fa-file-image-o'
    when 'application/pdf'
      'fa fa-file-pdf-o'
    when 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      'fa fa-file-word-o'
    when 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      'fa fa-file-excel-o'
    when 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      'fa fa-file-powerpoint-o'
    when 'video/x-ms-asf', 'video/x-msvideo', 'video/x-flv', 'video/mp4', 'video/quicktime', 'video/x-ms-wmv'
      'fa fa-file-video-o'
    when 'application/x-zip-compressed', 'application/zip'
      'fa fa-file-archive-o'
    else
      'fa fa-file-o'
    end
  end

  def parent_document_folder_options(folder=nil)
    DocumentFolder.where.not(id: folder.try(:id) || 0)
      .order(:path)
      .reject { |f| f.parent_folder_ids.include?(folder.try(:id)) }
      .map { |f| [f.path, f.id] }
  end

end

app/views/documents/_folder_form.haml
= form_for @folder, as: :folder, url: @folder.new_record? ? documents_path : document_path(@folder) do |form|
  = error_messages_for(form)
  = form.hidden_field :folder_id
  - if parent_document_folder_options(@folder).any?
    .form-group
      = form.label :folder_id
      = form.select :folder_id, parent_document_folder_options(@folder), { include_blank: true }, class: 'form-control'
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control'
  .form-group
    = form.button t('save'), class: 'btn btn-success'

app/views/documents/_form.haml
= form_for @document, multipart: true do |form|
  = error_messages_for(form)
  = form.hidden_field :folder_id
  - if parent_document_folder_options.any?
    .form-group
      = form.label :folder_id
      = form.select :folder_id, parent_document_folder_options, { include_blank: true }, class: 'form-control'
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control'
  .form-group
    = form.label :file
    = form.file_field :file
  .form-group
    = form.button t('save'), class: 'btn btn-success'

app/views/documents/edit.html.haml
- @title = t('.heading', document: @document.name)

= render partial: 'form'

app/views/documents/edit_folder.html.haml
- @title = t('.heading', folder: @folder.name)

= render partial: 'folder_form'

app/views/documents/index.html.haml
- @title = @parent_folder.try(:name) || t('.heading')

%p
  = @parent_folder.try(:description) || t('.intro')

- if @folders.any? or @documents.any?
  %table.table
    %tr
      %th
      %th= t('.table.name')
      %th= t('.table.updated_at')
      %th= t('.table.size')
      %th
    - @folders.each do |folder|
      %tr
        %td
          = link_to documents_path(folder_id: folder.id) do
            = icon 'fa fa-folder'
        %td
          = link_to documents_path(folder_id: folder.id) do
            = folder.name
        %td
          = folder.updated_at.to_s(:full)
        %td
          = t('.table.item_count', count: folder.item_count)
        %td.actions
          - if @logged_in.admin?(:manage_documents)
            = link_to edit_document_path(folder, folder: true), class: 'btn btn-info btn-xs' do
              = icon 'fa fa-pencil'
            = link_to document_path(folder, folder: true), data: { method: 'delete', confirm: t('documents.delete_folder.confirmation') }, class: 'btn btn-delete btn-xs' do
              = icon 'fa fa-trash-o'
      %tr.description
        %td
        %td{ colspan: 4 }
          = folder.description
    - @documents.each do |document|
      %tr
        %td
          = link_to document_path(document.id) do
            = icon document_icon_class(document)
        %td
          = link_to document_path(document.id) do
            = document.name
        %td
          = document.updated_at.to_s(:full)
        %td
          = number_to_human_size(document.file.try(:size) || 0)
        %td.actions
          - if @logged_in.admin?(:manage_documents)
            = link_to edit_document_path(document), class: 'btn btn-info btn-xs' do
              = icon 'fa fa-pencil'
            = link_to document_path(document), data: { method: 'delete', confirm: t('are_you_sure') }, class: 'btn btn-delete btn-xs' do
              = icon 'fa fa-trash-o'
      %tr.description
        %td
        %td{ colspan: 4 }
          = document.description
- else
  %em= t('none')

- if @logged_in.admin?(:manage_documents)
  .page-controls.push-down
    = link_to new_document_path(folder: true, folder_id: @parent_folder), class: 'btn btn-success' do
      = icon 'fa fa-folder'
      = t('.new_folder.button')
    = link_to new_document_path(folder_id: @parent_folder), class: 'btn btn-success' do
      = icon 'fa fa-file'
      = t('.new_document.button')

app/views/documents/new.html.haml
- @title = t('.heading')

= render partial: 'form'

app/views/documents/new_folder.html.haml
- @title = t('.heading')

= render partial: 'folder_form'

app/views/documents/show.html.haml
- @title = @document.name

%p
  = @document.description

.text-center.well
  - if @document.image?
    = link_to download_document_path(@document, inline: true) do
      = image_tag(download_document_path(@document, inline: true))
  - else
    = link_to download_document_path(@document) do
      = icon document_icon_class(@document) + ' icon-huge'

%table.table
  %tr
    %td= t('.table.filename')
    %td= @document.file_file_name
  %tr
    %td= t('.table.content_type')
    %td= @document.file.content_type
  %tr
    %td= t('.table.size')
    %td= number_to_human_size @document.file.size
  %tr
    %td= t('.table.updated_at')
    %td= @document.updated_at.to_s(:full)
%p
  = link_to download_document_path(@document), class: 'btn btn-info' do
    = icon 'fa fa-download'
    = t('.download.button')